runtime: python310
env: standard
instance_class: F1
entrypoint: uvicorn main:app --host=0.0.0.0 --port=${PORT:-443}
automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  min_instances: 0
  min_idle_instances: 0
  min_pending_latency: 3000ms
  max_pending_latency: automatic