name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        DEEPL_API_KEY_FREE: ${{ secrets.DEEPL_API_KEY_FREE }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc
