name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: App Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        DEEPL_API_KEY_FREE: ${{ secrets.DEEPL_API_KEY_FREE }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
